#!/usr/bin/env python3
"""Полугодовое напоминание разобрать зависимости — issue с чеклистом.

ЗАЧЕМ ВООБЩЕ. Еженедельная сверка пинов (`pins.yml`) отвечает на вопрос «вышло ли что-то
новее». Она НЕ отвечает на вопросы, которые накапливаются медленно: жив ли ещё апстрим,
не сменилась ли лицензия, не смержили ли чужой патч, который мы держим у себя. Такие
вещи не ломаются в конкретный день, поэтому их не замечают вовсе — ровно до момента,
когда они уже дорогие.

ЗАЧЕМ РАЗ В ПОЛГОДА. Чаще — превращается в фоновый шум, который закрывают не читая;
реже — успевает протухнуть слишком многое. Раз в полгода расходы на разбор ощутимы, но
не привычны, и его делают всерьёз.

ЗАЧЕМ ISSUE, А НЕ СТРОКА В ДОКУМЕНТЕ. Строку в документе никто не читает по расписанию.
Issue попадает в список задач. Тот же довод, что и в `report-pin-drift.py`.

Если прошлый разбор ещё не закрыт — НЕ заводим второй, а комментируем существующий:
две одинаковые задачи в списке гарантированно приводят к тому, что закрывают обе не читая.

Запускается из .github/workflows/deps-review.yml. Переменные окружения: GH_TOKEN, REPO,
RUN_URL, а также DATE (дата запуска, ГГГГ-ММ-ДД — приходит из workflow, чтобы тело issue
было воспроизводимым).
"""
import json
import os
import sys
import urllib.error
import urllib.request

API = "https://api.github.com"
TITLE = "Полугодовой разбор зависимостей"

token = os.environ["GH_TOKEN"]
repo = os.environ["REPO"]
run_url = os.environ.get("RUN_URL", "")
date = os.environ.get("DATE", "")

HEADERS = {
    "Authorization": f"Bearer {token}",
    "Accept": "application/vnd.github+json",
    "User-Agent": "bee2-tls-gateway-deps-review",
}


def api(method, path, payload=None):
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(f"{API}{path}", data=data, headers=HEADERS, method=method)
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read() or "null")


CHECKLIST = """## Чеклист

### Версии и уязвимости

- [ ] `bee2evp`, `bee2`, OpenSSL, nginx, базовый образ Debian — вышли ли новые версии,
      есть ли CVE на те, что стоят у нас. Отчёт еженедельной сверки — issue «Пины отстали
      от апстрима», но здесь нужен ВЗГЛЯД, а не факт: новее не значит лучше.
- [ ] Ветки поддержки не кончились: OpenSSL 3.5 — LTS до 2030, nginx stable, Debian 12.

### Жив ли апстрим

- [ ] `agievich/bee2` и `bcrypto/bee2evp` — когда последний коммит, отвечает ли мейнтейнер
      на issue. Проект, в который полгода никто не коммитил, — это уже риск, а не удобство.
- [ ] Наши открытые вопросы к апстриму сдвинулись?

### Чужие патчи, которые мы держим у себя

- [ ] `patches/` — смержен ли патч в апстриме. **Смержен → патч удалить и сдвинуть пин**,
      иначе мы годами тащим форк, которого не хотели.
- [ ] `agievich/bee2` [PR #77](https://github.com/agievich/bee2/pull/77) (busy-loop потока
      `jitter`, наша issue #8) — статус.
- [ ] Обход бага `scripts/source.sh` в `Dockerfile` (`sed` про `-eq "Debug"`) — исправлен
      ли у bee2evp.

### Лицензии

- [ ] Лицензии апстримов не менялись, `NOTICE` актуален. Смена лицензии в новой версии —
      обычное дело, а узнаётся она позже всего.

### Сертификация

- [ ] Появились ли методики испытаний по СТБ 34.101.27 и 34.101.78 (их не было —
      `docs/CERTIFICATION.md` §10.1).
- [ ] Реестр сертификатов ОАЦ: появились ли изделия на bee2evp.

### Проверка

- [ ] `bash scripts/check-crypto.sh --build` — зелёный.
- [ ] Итог разбора записать в `docs/PROCESS.md` §5, состояние — в `docs/PROJECT_MAP.md`.
"""


def body_for(kind):
    when = f" ({date})" if date else ""
    if kind == "new":
        head = f"Подошёл срок полугодового разбора зависимостей{when}."
    else:
        head = (
            f"Подошёл следующий срок полугодового разбора{when}, а прошлый ещё не закрыт.\n\n"
            "Вторую задачу не завожу намеренно: две одинаковые в списке приводят к тому, "
            "что закрывают обе не читая. Если прошлый разбор устарел — перечитать чеклист "
            "заново, он ниже."
        )
    return f"""{head}

{CHECKLIST}
[Прогон, который это завёл]({run_url})

---
_Generated by [Claude Code](https://claude.ai/code)_
"""


existing = None
for item in api("GET", f"/repos/{repo}/issues?state=open&per_page=100") or []:
    if item.get("title") == TITLE and "pull_request" not in item:
        existing = item["number"]
        break

try:
    if existing:
        api("POST", f"/repos/{repo}/issues/{existing}/comments", {"body": body_for("again")})
        print(f"прошлый разбор #{existing} ещё открыт — добавлен комментарий")
    else:
        created = api("POST", f"/repos/{repo}/issues", {"title": TITLE, "body": body_for("new")})
        print(f"заведена issue #{created['number']}")
except urllib.error.HTTPError as exc:
    print(f"FAIL не удалось записать issue: HTTP {exc.code} {exc.read()[:200]!r}", file=sys.stderr)
    sys.exit(1)
