#!/usr/bin/env python3
"""Отчёт о расхождении пинов — в issue, а не в историю прогонов.

ЗАЧЕМ ОТДЕЛЬНЫМ ФАЙЛОМ. Тело issue содержит кавычки, обратные апострофы, переводы строк
и кириллицу. Собирать его в shell внутри YAML — это два уровня экранирования подряд, и
ошибка там не роняет шаг, а тихо портит текст: issue заводится, но читать её невозможно.

ЗАЧЕМ ВООБЩЕ ISSUE. Задача #5 говорит прямо: у того, что джоба сообщает, должен быть
адресат, который это читает; красная джоба в репозитории, куда никто не смотрит, — то же
самое, что отсутствие джобы. Issue попадает в список задач, история прогонов — нет.

Одна issue на всё время: при повторном расхождении она обновляется, а не заводится заново.
Иначе через месяц в списке будет четыре одинаковых, и их начнут закрывать не читая.

Запускается из .github/workflows/pins.yml. Переменные окружения: GH_TOKEN, REPORT, REPO,
RUN_URL.
"""
import json
import os
import sys
import urllib.error
import urllib.request

API = "https://api.github.com"
TITLE = "Внешние зависимости требуют внимания"

token = os.environ["GH_TOKEN"]
repo = os.environ["REPO"]
report = os.environ.get("REPORT", "(отчёт пуст)")
run_url = os.environ.get("RUN_URL", "")

HEADERS = {
    "Authorization": f"Bearer {token}",
    "Accept": "application/vnd.github+json",
    "User-Agent": "bee2-tls-gateway-pins",
}


def api(method, path, payload=None):
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(f"{API}{path}", data=data, headers=HEADERS, method=method)
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read() or "null")


body = f"""Еженедельная сверка нашла что-то, требующее внимания: пины отстали от апстрима,
либо срокам связки ГосСУОК осталось меньше порога.

```
{report}
```

[Прогон, который это нашёл]({run_url})

⚠ **«Вышла новая версия» и «нам нужно обновиться» — разные утверждения.** У nginx свежий
mainline может быть хуже stable; у OpenSSL бамп невозможен, пока у bee2evp нет
`btls/patch/<тег>.patch` под новый тег — без него сборка просто не соберётся. Задача
сообщает факты, решение за человеком.

⚠ Строка `??` в отчёте — это **не** «всё в порядке»: значит проверить не удалось (сеть,
изменившаяся страница апстрима). Недоступная проверка, выглядящая как чистая, — обычный
способ для сторожа перестать сторожить.

⚠ Если строки про связку ГосСУОК говорят об истечении — **это не аварийная замена, а
плановая**. Корни меняются набором: новый кладётся рядом со старым заранее, старый
убирается после перехода, простоя нет. Порядок — `docs/PROCESS.md` §4.

Порядок действий при бампе пина, включая то, как снимать и сверять `sha256` двумя
способами, — `docs/PROCESS.md` §5, запись про уход nginx с legacy-ветки.

---
_Generated by [Claude Code](https://claude.ai/code)_
"""

# Ищем свою открытую issue по точному заголовку. Эндпоинт отдаёт и pull request'ы —
# отсеиваем по наличию ключа `pull_request`.
existing = None
for item in api("GET", f"/repos/{repo}/issues?state=open&per_page=100") or []:
    if item.get("title") == TITLE and "pull_request" not in item:
        existing = item["number"]
        break

try:
    if existing:
        api("PATCH", f"/repos/{repo}/issues/{existing}", {"title": TITLE, "body": body})
        print(f"обновлена issue #{existing}")
    else:
        created = api("POST", f"/repos/{repo}/issues", {"title": TITLE, "body": body})
        print(f"заведена issue #{created['number']}")
except urllib.error.HTTPError as exc:
    print(f"FAIL не удалось записать issue: HTTP {exc.code} {exc.read()[:200]!r}", file=sys.stderr)
    sys.exit(1)
